"use client"
import './globals.css'
import { Montserrat } from 'next/font/google'
import { AnimatePresence } from 'framer-motion'
import { usePathname, useRouter } from 'next/navigation';
import Navbar1 from './component/Navbar1';
import Layout from './component/Layout'



const mont = Montserrat(
  
  { subsets: ['latin'] ,
  variable: '--font-mont',
  weight: ['400' ,'700'],
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const router = usePathname();

  return (
    <html lang="en">
   
      <body suppressHydrationWarning={true}>

      <main className={mont.className}>
      <Layout className=''>
          <Navbar1/>
      <AnimatePresence mode='wait' key={router}> 
        {children} 
        </AnimatePresence>
        </Layout>
      
      </main>
        </body>
      
    </html>
  )
}
